version: '3.8'
services:
  nextjs:
    build:
      context: ./Docker/Node/16/
    ports:
      - 3000:3000
    volumes:
      - ./packages/frontend:/home/node/app
    command:
      - /bin/sh
      - -c
      - |
        yarn install
        yarn build
        yarn start
    depends_on:
      - strapi
      - strapiDB

  strapi:
    build:
      context: ./Docker/Node/16/
    ports:
      - 1337:1337
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      NODE_ENV: ${NODE_ENV}

    volumes:
      - ./packages/backend/:/home/node/app
    command:
      - /bin/sh
      - -c
      - |
        yarn install
        yarn build
        yarn start
    depends_on:
      - strapiDB

  strapiDB:
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: .env
    image: postgres:12.0-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./Docker/postgres-data:/var/lib/postgresql/data/ #using a volume
